Document: ftimes
Title: Debian ftimes Manual
Author: <insert document author here>
Abstract: This manual describes what ftimes is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ftimes/ftimes.sgml.gz

Format: postscript
Files: /usr/share/doc/ftimes/ftimes.ps.gz

Format: text
Files: /usr/share/doc/ftimes/ftimes.text.gz

Format: HTML
Index: /usr/share/doc/ftimes/html/index.html
Files: /usr/share/doc/ftimes/html/*.html
